[build]
  base = "."
  publish = "apps/web/.next"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Эта настройка обеспечивает корректную работу страниц Next.js
    includeFiles = ["/apps/web/**"]

# Настройки разработки (локально)
[dev]
  command = "pnpm run dev"
  targetPort = 3000
  port = 8888
  publish = "apps/web/.next"

# Перенаправление для API запросов
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Обработка SPA роутинга Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
