packages:
  # Приложения
  - 'apps/*'
  # Общие пакеты
  - 'packages/*'
  # API
  - 'apps/api/*'
  # Web
  - 'apps/web/*'
  # Исключаем папку node_modules
  - '!**/node_modules/**'
  # Исключаем директории, начинающиеся с точки
  - '!**/.*/**'
