services:
  # API сервис (NestJS)
  - type: web
    name: questai-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install && pnpm run build:api
    startCommand: pnpm run start:api
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Другие переменные окружения добавляются через интерфейс Render
    autoDeploy: true

  # Web сервис (Next.js)
  - type: web
    name: questai-web
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:web
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: questai-api
          type: web
          property: url
      # Другие переменные окружения добавляются через интерфейс Render
    autoDeploy: true
