services:
  # API сервис (NestJS)
  - type: web
    name: questai-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install && pnpm run build:api
    startCommand: pnpm run start:api
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_IPS
        value: "176.64.6.69,172.71.192.151,10.201.129.68"
      - key: SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID
        value: "" # Заполнить через интерфейс Render
      - key: SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET
        value: "" # Заполнить через интерфейс Render
      # Другие переменные окружения добавляются через интерфейс Render
    autoDeploy: true

  # Web сервис (Next.js)
  - type: web
    name: questai-web
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:web
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: questai-api
          type: web
          property: url
          append: /api
      - key: BACKEND_IPS
        fromService:
          name: questai-api
          type: web
          property: ipAddresses
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: "" # Заполнить через интерфейс Render
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "" # Заполнить через интерфейс Render
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: "" # Заполнить через интерфейс Render
      # Другие переменные окружения добавляются через интерфейс Render
    autoDeploy: true
